import { test, expect } from '@playwright/test'
import { mockApp } from './fixtures'

test('native unlock opens automatically without a browser password and lock revokes access', async ({ page }) => {
  const unlockRequests: unknown[] = []
  page.on('request', request => { if (request.url().endsWith('/api/unlock')) unlockRequests.push(request.postDataJSON()) })
  await page.goto('/')
  await expect(page.getByRole('dialog', { name: 'Settings' })).toBeVisible()
  await expect(page.getByLabel('Passphrase', { exact: true })).toHaveCount(0)
  expect(unlockRequests[0]).toEqual({})
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Lock', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Locked', exact: true })).toBeVisible()
  const privateRead = await page.request.get('/api/state', { headers: { 'x-trilly': '1' } })
  expect(privateRead.status()).toBe(401)
  await expect(async () => {
    await page.getByRole('button', { name: 'Unlock', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Settings' })).toBeVisible({ timeout: 1000 })
  }).toPass({ timeout: 10000, intervals: [2200] })
  expect(unlockRequests.every(body => JSON.stringify(body) === '{}')).toBe(true)
})

test('cancelled macOS authentication stays locked and offers an explicit retry', async ({ page }) => {
  let prompts = 0
  await page.route('**/api/status', route => route.fulfill({ json: { exists: true, mode: 'macos' } }))
  await page.route('**/api/unlock', route => { prompts++; return route.fulfill({ status: 400, json: { error: 'Unlock cancelled or authentication denied' } }) })
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('Unlock cancelled')
  await expect(page.getByRole('heading', { name: 'Locked', exact: true })).toBeVisible()
  expect(prompts).toBe(1)
  await expect(page.locator('input[type="password"]')).toHaveCount(0)
  await page.keyboard.press('Enter')
  await expect.poll(() => prompts).toBe(2)
})

test('legacy migration requests only the old vault passphrase once', async ({ page }) => {
  let request: unknown
  await page.route('**/api/status', route => route.fulfill({ json: { exists: true, mode: 'migration' } }))
  await page.route('**/api/unlock', route => {
    request = route.request().postDataJSON()
    return route.fulfill({ status: 400, json: { error: 'Synthetic migration cancellation' } })
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Switch to macOS unlock' })).toBeVisible()
  expect(request).toBeUndefined()
  await page.getByLabel('Existing vault passphrase').fill('synthetic old vault passphrase')
  await page.getByRole('button', { name: 'Migrate', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Synthetic migration cancellation')
  expect(request).toEqual({ legacy_passphrase: 'synthetic old vault passphrase' })
})

test('one-key suggestions, category search, undo and skip', async ({ page }) => {
  const actions = await mockApp(page)
  await expect(page.getByRole('button', { name: /24 similar transactions/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Sync', exact: true })).toBeEnabled()
  await page.keyboard.press('2')
  await expect(page.getByRole('heading', { name: 'Brew House', exact: true })).toBeVisible()
  expect(actions.find(a => a.action === 'review')).toMatchObject({ id: 'one', payee_id: 'market', category_id: 'dining' })
  await page.keyboard.press('c')
  await page.getByRole('combobox', { name: 'Search category' }).fill('coff')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Category Coffee C' })).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Whole Foods', exact: true })).toBeVisible()
  expect(actions.filter(a => a.action === 'review')[1]).toMatchObject({ id: 'two', category_id: 'coffee' })
  await page.keyboard.press('u')
  await expect(page.getByRole('heading', { name: 'Brew House', exact: true })).toBeVisible()
  await page.keyboard.press('s')
  await expect(page.getByRole('heading', { name: 'Whole Foods', exact: true })).toBeVisible()
  await page.keyboard.press('s')
  await expect(page.getByRole('heading', { name: 'All remaining skipped' })).toBeVisible()
  await page.getByRole('button', { name: 'Review skipped' }).click()
  await expect(page.getByRole('heading', { name: 'Brew House', exact: true })).toBeVisible()
})

test('theme selection persists, follows system appearance, and stays within viewport', async ({ page }) => {
  await mockApp(page)
  await page.keyboard.press(',')
  await expect(page.getByRole('button', { name: 'Random', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Graphite', exact: true }).click()
  await page.getByLabel('Appearance').selectOption('system')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-color-scheme', 'dark')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'graphite')
  await expect(page).toHaveTitle('Trilly')
  await expect(page.locator('.brand')).toHaveText('trilly')
  await expect(page.locator('.brand')).toHaveCSS('color', 'rgb(56, 189, 248)')
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.screenshot({ path: 'test-results/review-dark.png', fullPage: true, animations: 'disabled' })
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-color-scheme', 'light')
  await page.screenshot({ path: 'test-results/review-light.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/review-mobile.png', fullPage: true, animations: 'disabled' })
  const storage = await page.evaluate(() => ({ ...localStorage }))
  expect(Object.keys(storage)).toEqual(['appearance'])
  expect(storage.appearance).not.toContain('synthetic')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'graphite')
})

test('failed sync leaves pending work visible and supports retry', async ({ page }) => {
  await mockApp(page, { syncError: true })
  await expect(page.getByRole('button', { name: 'Sync', exact: true })).toBeEnabled()
  await page.locator('.workspace').focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Brew House', exact: true })).toBeVisible()
  await page.keyboard.press('r')
  await expect(page.getByRole('alert')).toContainText('Changes remain saved locally')
  await expect(page.locator('.sync-state')).toHaveText('1 pending')
})

test('transfers only allow approval and lock clears displayed data', async ({ page }) => {
  await mockApp(page, { special: true })
  await expect(page.getByText('Transfer', { exact: true })).toBeVisible()
  await page.keyboard.press('c')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Edit in YNAB' })).toBeVisible()
  await page.keyboard.press('l')
  await expect(page.getByRole('heading', { name: 'Locked', exact: true })).toBeVisible()
  await expect(page.getByText('Whole Foods', { exact: true })).toHaveCount(0)
})

test('sync preserves a draft category and typing never triggers global shortcuts', async ({ page }) => {
  const actions = await mockApp(page)
  await expect(page.getByRole('button', { name: 'Sync', exact: true })).toBeEnabled()
  await page.keyboard.press('c')
  await page.getByRole('combobox', { name: 'Search category' }).fill('dining')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Category Dining out C' })).toBeVisible()
  await page.keyboard.press('r')
  await expect(page.getByRole('button', { name: 'Sync', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Category Dining out C' })).toBeVisible()
  await page.keyboard.press('p')
  await page.getByRole('combobox', { name: 'Search payee' }).fill('123surcl')
  await expect(page.getByText('No matches', { exact: true })).toBeVisible()
  expect(actions.filter(a => ['review', 'undo', 'lock'].includes(a.action as string))).toHaveLength(0)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
